config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ru/ do
    resources :posts
    resources :gifts
    resources :guests
    resources :rsvps

    devise_for :users

    root 'pages#home'

    get 'guestbook', to: 'posts#index'

    get 'rsvp', to: 'rsvps#new'

    get 'gift', to: 'gifts#new'

    get 'visa' => 'pages#visa'

    get 'location' => 'pages#location'

    resources :charges
  end
end

app/models/gift.rb
class Gift < ApplicationRecord
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :set_gift, only: [:show, :edit, :update, :destroy]

  require 'net/http'
  require 'json'

  # GET /gifts
  # GET /gifts.json
  def index
    @gifts = Gift.all
  end

  # GET /gifts/1
  # GET /gifts/1.json
  def show
    url = 'http://api.fixer.io/latest?base=USD'
    uri = URI(url)
    response = Net::HTTP.get(uri)
    exchange = JSON.parse(response)
    @nok = exchange['rates']['NOK'].to_f
    @rub = exchange['rates']['RUB'].to_f
    @gbp = exchange['rates']['GBP'].to_f

    # Amount in cents
    orig_amount = @gift.amount

    def convert_amount(orig_amount, currency)
      if currency == 'nok'
        ((orig_amount / @nok) * 100).floor
      elsif currency == 'rub'
        ((orig_amount / @rub) * 100).floor
      elsif currency == 'gbp'
        ((orig_amount / @gbp) * 100).floor
      else
        (orig_amount * 100).floor
      end
    end

    @amount = convert_amount(orig_amount, @gift.currency)
  end

  # GET /gifts/new
  def new
    @gift = Gift.new
  end

  # GET /gifts/1/edit
  def edit
  end

  # POST /gifts
  # POST /gifts.json
  def create
    @gift = Gift.new(gift_params)

    respond_to do |format|
      if @gift.save
        format.html { redirect_to @gift, notice: 'Gift was successfully created.' }
        format.json { render :show, status: :created, location: @gift }
      else
        format.html { render :new }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifts/1
  # PATCH/PUT /gifts/1.json
  def update
    respond_to do |format|
      if @gift.update(gift_params)
        format.html { redirect_to @gift, notice: 'Gift was successfully updated.' }
        format.json { render :show, status: :ok, location: @gift }
      else
        format.html { render :edit }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifts/1
  # DELETE /gifts/1.json
  def destroy
    @gift.destroy
    respond_to do |format|
      format.html { redirect_to gifts_url, notice: 'Gift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gift
      @gift = Gift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gift_params
      params.require(:gift).permit(:amount, :currency)
    end
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/views/gifts/_form.html.erb
<div class="form_content_rsvp">
<%= form_with(model: gift, local: true) do |form| %>
  <% if gift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gift.errors.count, "error") %> <%= I18n.t "gifts.error_message" %></h2>

      <ul>
      <% gift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form_section">
      <div class="left12">
        <div class="form_row_full">
      <label><%= I18n.t "gifts.amount" %></label>
      <%= form.number_field :amount, id: :gift_amount, class: 'form_input required' %>
      </div>
    </div>

      <div class="left12_last">
        <div class="form_row_full">
        <label><%= I18n.t "gifts.currency" %></label>
        <div class="select_container">
        <%= form.select :currency, [["RUB", "rub"], ["NOK", "nok"], ["GBP", "gbp"], ["USD", "usd"]], id: :gift_currency %>
        </div>
        </div>
      </div>

      <div class="full_width">
        <center>
          <%= form.submit t("gifts.payment_button"), class: 'form_submit_contact'  %>
        </center>
      </div>
 </div>
<% end %>
</div>

app/views/gifts/edit.html.erb
<h1>Editing Gift</h1>

<%= render 'form', gift: @gift %>

<%= link_to 'Show', @gift %> |
<%= link_to 'Back', gifts_path %>

app/views/gifts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gifts</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Currency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gifts.each do |gift| %>
      <tr>
        <td><%= gift.amount %></td>
        <td><%= gift.currency %></td>
        <td><%= link_to 'Show', gift %></td>
        <td><%= link_to 'Edit', edit_gift_path(gift) %></td>
        <td><%= link_to 'Destroy', gift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gift', new_gift_path %>

app/views/gifts/new.html.erb
<div class="section_centered">

	 <div class="centered_title">
      <h2 style="font-family: Lobster; font-size: 50px"><%= I18n.t "gifts.main_title" %></h2>
   </div>

  <%= render 'form', gift: @gift %>

</div>

app/views/gifts/show.html.erb
<div class="section_centered">

   <h3><%= I18n.t "gifts.giving" %> <%= @gift.amount %> <%= @gift.currency %>. <%= I18n.t "gifts.converted" %>.</h3>

   <%= form_tag charges_path(gift: @gift) do %>
     <center>
       <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
             data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
             data-description="<%= I18n.t "gifts.stripe_desc" %>"
             data-amount="<%= @amount %>"
             data-locale="auto"></script>
      </center>
   <% end %>

</div>