config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ru/ do
    resources :posts
    resources :gifts
    resources :guests
    resources :rsvps

    devise_for :users

    root 'pages#home'

    get 'guestbook', to: 'posts#index'

    get 'rsvp', to: 'rsvps#new'

    get 'gift', to: 'gifts#new'

    get 'visa' => 'pages#visa'

    get 'location' => 'pages#location'

    resources :charges
  end
end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
  has_many :guests, dependent: :destroy
  accepts_nested_attributes_for :guests, allow_destroy: true, reject_if: :all_blank

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :phone_number, presence: true
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  before_action :set_rsvp, only: [:show, :edit, :update, :destroy]

  # GET /rsvps
  # GET /rsvps.json
  def index
    @rsvps = Rsvp.all
  end

  # GET /rsvps/1
  # GET /rsvps/1.json
  def show
  end

  # GET /rsvps/new
  def new
    @rsvp = Rsvp.new
    @rsvp.guests.build
  end

  # GET /rsvps/1/edit
  def edit
    @rsvp.guests.build
  end

  # POST /rsvps
  # POST /rsvps.json
  def create
    @rsvp = Rsvp.new(rsvp_params)

    respond_to do |format|
      if @rsvp.save
        format.html { redirect_to @rsvp, notice: 'Rsvp was successfully created.' }
        format.json { render :show, status: :created, location: @rsvp }
      else
        format.html { render :new }
        format.json { render json: @rsvp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rsvps/1
  # PATCH/PUT /rsvps/1.json
  def update
    respond_to do |format|
      if @rsvp.update(rsvp_params)
        format.html { redirect_to @rsvp, notice: 'Rsvp was successfully updated.' }
        format.json { render :show, status: :ok, location: @rsvp }
      else
        format.html { render :edit }
        format.json { render json: @rsvp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rsvps/1
  # DELETE /rsvps/1.json
  def destroy
    @rsvp.destroy
    respond_to do |format|
      format.html { redirect_to rsvps_url, notice: 'Rsvp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rsvp
      @rsvp = Rsvp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rsvp_params
      params.require(:rsvp).permit(:first_name, :last_name, :email, :phone_number, :transportation, :coming, :comments, guests_attributes: [:id, :_destroy, :rsvp_id, :first_name, :last_name])
    end
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/views/rsvps/_form.html.erb
<div class="form_content_rsvp">
      <h3 class="form_toptitle" id="Note"></h3>
      <%= simple_form_for(@rsvp) do |f| %>
      <% if rsvp.errors.any? %>
    <div id="error_explanation">
      <h2 style="color: #ef6350"><%= I18n.t "rsvp.errors.please" %></h2>
    </div>
  <% end %>

  <center>
  <div class="form_section">

    <h6>Быть или не быть?</h6>
    <%= f.select :coming, [["Я приеду", true], ["Не смогу приехать", false]], class: "form_input required" %>

  </div>
  </center>


      <div class="form_section">
          <div class="form_row left14">
          <label><%= I18n.t "rsvp.form.first_name" %></label>
          <%= f.text_field :first_name, id: :rsvp_first_name, class: 'form_input required', placeholder: t("rsvp.form.first_name_placeholder") %>
          </div>
          <div class="form_row left14">
          <label><%= I18n.t "rsvp.form.last_name" %></label>
          <%= f.text_field :last_name, id: :rsvp_last_name, class: 'form_input required', placeholder: t("rsvp.form.last_name_placeholder") %>
          </div>
          <div class="form_row left14">
          <label><%= I18n.t "rsvp.form.email" %></label>
          <%= f.text_field :email, id: :rsvp_email, class: 'form_input required email', placeholder: t("rsvp.form.email_placeholder") %>
          </div>
          <div class="form_row left14_last">
          <label><%= I18n.t "rsvp.form.phone" %></label>
          <%= f.text_field :phone_number, id: :rsvp_phone_number, class: 'form_input required', placeholder: t("rsvp.form.phone_placeholder") %>
          </div>


  <center>
    <div class="form_section">
      <h6>Как поедете?</h6>
      <%= f.select :transportation, [["На машине", 0], ["На электричке", 1], ["На автобусе для гостей", 2], ["ННе знаю", 3]], class: "form_input required" %>
    </div>
  </center>



          <div class="form_row left12" style="margin-top: 30px">
          <label><%= I18n.t "rsvp.form.other_comments" %></label>
          <%= f.text_area :comments, id: :rsvp_comments, class: 'form_textarea_full', placeholder: t("rsvp.form.other_comments_placeholder") %>
          </div>
          <div class="form_row left12_last" style="margin-top: 50px">
            <label><%= I18n.t "rsvp.form.add_guests" %></label>
            <table class="table">
              <thead>
                <tr>
                  <th></th>
                  <th><%= I18n.t "rsvp.form.guests.first_name" %></th>
                  <th><%= I18n.t "rsvp.form.guests.last_name" %></th>
                </tr>
              </thead>
              <tbody class="fields">
                <%= f.simple_fields_for :guests do |builder| %>
                  <%= render 'guest', f: builder %>
                <% end %>
              </tbody>
            </table>
            <div class="">
              <%= link_to_add_row(t("rsvp.form.guests.add_guest_button"), f, :guests, class: 'simple_button fade-page') %>
            </div>
          </div>
     </div>
       <center>
         <%= f.submit t("rsvp.form.rsvp_button"), class: 'simple_button fade-page', style: "font-size: 20px" %>
       </center>
      <% end %>
</div>

<script>
$(document).on('turbolinks:load', function() {

  $('form').on('click', '.add_fields', function(event) {
    $(this).prev('input[type=hidden]').val('1');
    $(this).closest('tr').hide();
    return event.preventDefault();
  });

  $('form').on('click', '.add_fields', function(event) {
    var regexp, time;
    time = new Date().getTime();
    regexp = new RegExp($(this).data('id'), 'g');
    $('.fields').append($(this).data('fields').replace(regexp, time));
    return event.preventDefault();
  });
});
</script>

app/views/rsvps/_guest.html.erb
<tr>
  <td>
    <%= f.input_field :_destroy, as: :hidden %>
    <%= link_to t("rsvp.form.guests.delete"), '#', class: 'remove_record' %>
  </td>
  <td><%= f.input :first_name, label: false %></td>
  <td><%= f.input :last_name, label: false %></td>
</tr>

app/views/rsvps/edit.html.erb
<h1>Editing Rsvp</h1>

<%= render 'form', rsvp: @rsvp %>

<%= link_to 'Show', @rsvp %> |
<%= link_to 'Back', rsvps_path %>

app/views/rsvps/index.html.erb
<% controller.redirect_to '/rsvp' %>

app/views/rsvps/new.html.erb
<div class="section_centered">
	 <div class="centered_title">
      <h2 style="font-family: Lobster"><%= I18n.t "rsvp.title.save" %> <span style="font-family: Lobster"><%= I18n.t "rsvp.title.your" %></span> <%= I18n.t "rsvp.title.place" %></h2>
   </div>

	 <%= render 'form', rsvp: @rsvp %>
</div>

app/views/rsvps/show.html.erb
<div class="section_centered">


	<% if @rsvp.coming == true %>
		 <div class="centered_title">
	     <h3><%= I18n.t "rsvp.thanks" %></h3>
			 <center><%= image_tag 'weddingcrashers.gif' %></center>
	  </div>
	<% else %>
		<div class="centered_title">
			<h3><%= I18n.t "rsvp.sad" %></h3>
			<center><%= image_tag 'sad.gif' %></center>
	 </div>
	<% end %>

</div>